library(oligo);
library(aroma.affymetrix);
source("init.R");
source("ui.R");

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
# Select data sets
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
paths <- c("raw");
pattern <- "_(199|200)[0-9]";
if (exists("dataSets", mode="list")) {
  ds <- dataSets[[1]];
  name <- paste(getName(ds), paste(getTags(ds), collapse=","), sep=",");
  ans <- menu(c("<new data sets>", name), title="Select data set(s) to process:");
  if (ans == 1)
    dataSets <- selectDataSets(paths, pattern=pattern);
} else {
  dataSets <- selectDataSets(paths, pattern=pattern);
}

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
# Process
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
res <- list();
for (kk in seq(along=dataSets)) {
  ds <- dataSets[[kk]];
  verbose && print(verbose, ds);

  sc <- PcrProbeCalibration(ds);
  print(sc);

  dsC <- process(sc, verbose=verbose);

  res[[kk]] <- dsC;
}


