/***********************************************************************
 * The file samples.js was automatically generated by aroma.affymetrix.
 * Do not edit this file!
 ***********************************************************************/

/* Samples */

explorer.onLoad = function() {
  this.setAliases(new Array('A01', 'A02'));
  this.setSamples(new Array('01', '02'));

/* Detected chip types */
  this.setChipTypes(new Array('Mouse430_2', 'Mouse430_3'));

/* Detected chip types */
  this.setColorMaps(new Array('gray', 'terrain'));

  return(false);
}



